export const countryCodes = [
  { code: "+1", country: "US", label: "United States" },
  { code: "+1", country: "CA", label: "Canada" },
  { code: "+44", country: "GB", label: "United Kingdom" },
  { code: "+91", country: "IN", label: "India" },
  { code: "+61", country: "AU", label: "Australia" },
  { code: "+49", country: "DE", label: "Germany" },
  { code: "+33", country: "FR", label: "France" },
  { code: "+81", country: "JP", label: "Japan" },
  { code: "+86", country: "CN", label: "China" },
  { code: "+82", country: "KR", label: "South Korea" },
  { code: "+65", country: "SG", label: "Singapore" },
  { code: "+971", country: "AE", label: "UAE" },
  { code: "+966", country: "SA", label: "Saudi Arabia" },
  { code: "+972", country: "IL", label: "Israel" },
  { code: "+55", country: "BR", label: "Brazil" },
  { code: "+52", country: "MX", label: "Mexico" },
  { code: "+234", country: "NG", label: "Nigeria" },
  { code: "+27", country: "ZA", label: "South Africa" },
  { code: "+254", country: "KE", label: "Kenya" },
  { code: "+62", country: "ID", label: "Indonesia" },
  { code: "+60", country: "MY", label: "Malaysia" },
  { code: "+63", country: "PH", label: "Philippines" },
  { code: "+66", country: "TH", label: "Thailand" },
  { code: "+84", country: "VN", label: "Vietnam" },
  { code: "+48", country: "PL", label: "Poland" },
  { code: "+31", country: "NL", label: "Netherlands" },
  { code: "+46", country: "SE", label: "Sweden" },
  { code: "+47", country: "NO", label: "Norway" },
  { code: "+45", country: "DK", label: "Denmark" },
  { code: "+41", country: "CH", label: "Switzerland" },
  { code: "+39", country: "IT", label: "Italy" },
  { code: "+34", country: "ES", label: "Spain" },
  { code: "+351", country: "PT", label: "Portugal" },
  { code: "+7", country: "RU", label: "Russia" },
  { code: "+380", country: "UA", label: "Ukraine" },
  { code: "+90", country: "TR", label: "Turkey" },
  { code: "+20", country: "EG", label: "Egypt" },
  { code: "+92", country: "PK", label: "Pakistan" },
  { code: "+880", country: "BD", label: "Bangladesh" },
  { code: "+94", country: "LK", label: "Sri Lanka" },
  { code: "+977", country: "NP", label: "Nepal" },
] as const;
